env: local
http_server:
  host: localhost
  port: 8090
storage:
  host: localhost
  port: 5432
  user: postgres
  password: supersecretpassword
  dbname: postgres
  sslmode: disable
jwt:
  secret: GPfYIQUkGexayJilJyz6brI0mthApP3HMUG